spring:

  jpa:

    database: POSTGRESQL
    show-sql: true

    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/online_store
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
server:
  port: 8082


